name: 're:think'
favicon: null
layout_spectrum: 0.010984905296936631
typography_spectrum: 0.862994002411142
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7367545000743121
  lightness: 0.66164844436571
  saturation: 0.5061281453818083
  rhythmicContrast: 0.5035313609987497
purpose: []
